import "./globals.css";
import SessionProvider from "@/app/components/sessionProvider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" data-theme="forest">
			<body>
				<div className="prose w-full max-w-none">
					<SessionProvider>{children}</SessionProvider>
				</div>
			</body>
		</html>
	);
}
