import "./globals.css";
import SessionProvider from "@/app/components/sessionProvider";
import QueryWrapper from "./components/queryWrapper";
import { getUser } from "@/server/user";
import Navigation from "./components/navigation";
export const metadata = {
	title: "Lead Gen App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	await getUser();
	return (
		<html lang="en" data-theme="light">
			<body>
				<Navigation />
				<div className="prose w-full max-w-none p-8 border-t-2">
					<SessionProvider>
						<QueryWrapper>{children}</QueryWrapper>
					</SessionProvider>
				</div>
			</body>
		</html>
	);
}
